# names = ['Mr. Teacher', 'Antonio Banderas', 'Cynthia Erivo', 'Scarlett Johansson', 'Jonathan Pryce', 'Florence Pugh', 'Yalitza Aparicio', 'Olivia Colman', 'Marina de Tavira', 'Adam Driver', 'Sam Elliott', 'Lady Gaga', 'Richard E. Grant', 'Regina King', 'Rami Malek', 'Mary J. Blige', 'Timothee Chalamet', 'Allison Janney', 'Daniel Kaluuya', 'Lesley Manville', 'Laurie Metcalf', 'Margot Robbie', 'Sam Rockwell', 'Mahershala Ali', 'Anderew Garfield', 'Naomie Harris', 'Lucas Hedges', 'Isabelle Huppert', 'Ruth Negga', 'Dev Patel', 'Bryan Cranston', 'Tom Hardy', 'Brie Larson', 'Jennifer Jason Leigh', 'Rachel McAdams', 'Charlotte Rampling', 'Mark Rylance', 'Alicia Vikander', 'Patricia Arquette', 'Steve Carell', 'Benedict Cumberbatch', 'Felicity Jones', 'Michael keaton', 'Rosamund Pike', 'Eddie Redmayne', 'J. K. Simmons', 'Emma Stone', 'Barkhad Abdi', 'Chiwetel Ejiofor', 'Michael Fassbender', 'Sally Hawkins', 'Jared Leto', 'Matthew McConaughey', 'Lupita Nyong\'o', 'June Squibb', 'Bradley Cooper', 'Hugh Jackman', 'Emmanuelle Riva', 'Quvenzhane Wallis', 'Berenice Bejo', 'Demian Bichir', 'Jessica Chastain', 'Jean Dujardin', 'Jonah Hill', 'Rooney Mara', 'Melissa McCarthy', 'Gary Oldman', 'Octavia Spencer', 'Christian Bale', 'Jesse Eisenberg', 'James Franco', 'John Hawkes', 'Jennifer Lawrence', 'Mark Ruffalo', 'Hailee Steinfeld', 'Jacki Weaver', 'Sandra Bullock', 'Vera Farmiga', 'Colin Firth', 'Maggi Gyllenhaal', 'Anna Kendrick', 'Mo\'Nique', 'Carey Mulligan', 'Christopher Plummer', 'Jeremy Renner', 'Gabourey Sidibe', 'Stanley Tucci', 'Christoph Waltz', 'Josh Brolin', 'Viola Davis', 'Anne Hathaway', 'Taraji P. Henson', 'Richard Jenkins', 'Frank Langella', 'Melissa Leo', 'Mickey Rourke', 'Michael Shannon', 'Casey Affleck', 'Marion Cotillard', 'Ruby Dee', 'Hal Holbrook', 'Viggo Mortensen', 'Ellen Page', 'Saoirse Ronan', 'Tilda Swinton']

names = [
  '金八先生',
  '大木 花子',
  '里田 浩介',
  '清原 幸子',
  '太田 エミリ',
  '金田 杏',
  'ヤン スリヤマ',
  '佐久間 敏也',
  'リリアン カイザー',
  '笠木 三郎',
  '宮下 徹',
  '栗木 義三',
  '秋田 佐枝',
  '小田 早苗',
  '木下 龍臣',
  '寺内 すすむ',
  '樫田 欽也',
  '稲田 理恵子',
  '岡田 奈津子',
  '中田 五月',
  '佐藤 良子',
  '室田 湊',
  'ウジョモ ハリオビッチ',
  '家入 一也',
  '渡辺 梅子',
  '城田 仁志',
  '甲田 洋介',
  '水谷 菊子',
  '久保 美樹',
  '安井 陽一',
  '野崎 愛',
  '坂田 太郎',
  '福岡 勝夫',
  '足立 亮',
  '村岡 裕恵',
  '青柳 美佐',
  '今野 学',
  '田村 邦彦',
  '富永 誠',
  '北原 たけし',
  '鈴木 咲子',
  '相沢 登',
  'ジョン ハンコック',
  '松谷 貴理子',
  '樺島 伊都子',
  '長野 亘',
  '山川 玲子',
  '小柳 利子',
  '菅野 林造',
  '湯浅 健吾',
  '荒川 丈一郎',
  'ソルボンヌ ディアス',
  'フリウリ ガスコイン',
  'ディナ ターレ',
  '小野 松矢',
  '梶取 映子',
  '田辺 オリエ',
  '藤田 宗二',
  '片岡 花子',
  '西野 寛',
  '鳥海 ひろし',
  'アリアナ サポ',
  '大川 マリア',
  '川島 あきら',
  '戸川 克伸',
  '飯尾 ずん',
  '田原 俊彦',
  '杉田 かおる',
  '南川 義嗣',
  '東 ひばり',
  '日高 栄介',
  '小畠 春',
  '北西 けんじ',
  'チョウ ヨンピル',
  '須田 清子',
  '佐賀 康子',
  'スカーレット ファンドラント',
  '金子 義男',
  '初川 歳二郎',
  '南部 小吉',
  '和田 昭夫',
  '小野寺 歌子',
  '相川 宗佑',
  '水戸 五朗',
  '堀 宮子',
  '高橋 知美',
  '北澤 和宏',
  '浜田 典利',
  '有岡 伸也',
  '北斗 リアナ',
  'グラッセン ノイヤー',
  '岡島 岳',
  '内海 香子',
  'オリビエ ジルー',
  '張田 修',
  '堀田 銀次',
  '代田 定次',
  '工藤 淳',
  '長谷川 文子',
  '半田 佐三',
]

names.each_with_index {|name, i|
  uid = sprintf "user%03d", i
  User.create(username: uid, fullname: name, password: '123456', role: ((i == 0) ? 'teacher' : 'student'))
  Visit.create(user_id: 1, visitee: i)
}